Repository kadena-io/chainweb-node, pull requests merged in 2020-04, with the labels that each got.

#996 Fix testnet fork points
  src/Chainweb/Version.hs
  test/Chainweb/Test/BlockHeader/Validation.hs
Labels: component:core

#997 support ghc-8.10.1
  .github/workflows/applications.yml
  cabal.project
  chainweb.cabal
  dep/kpkgs/github.json
  src/Chainweb/Chainweb.hs
  src/Chainweb/Chainweb/PeerResources.hs
  src/Chainweb/Logger.hs
  src/Chainweb/Logging/Config.hs
  stack.yaml
  tools/db-checksum/CheckpointerDBChecksum.hs
Labels: component: project-config

#1000 LTS 15
  .github/workflows/stack-ci.yaml
  chainweb.cabal
  stack.yaml
Labels: component: project-config

#974 Feature Flag Validation
  src/Chainweb/Version.hs
  test/Chainweb/Test/BlockHeader/Validation.hs
Labels: Fork, component:core
