Repository kadena-io/chainweb-node, pull requests merged in 2020-03, with the labels that each got.

#948 Fix typo
  src/Chainweb/RestAPI.hs
  src/Utils/Logging.hs
Labels: documentation

#952 Fix typo
  src/Chainweb/Pact/PactService.hs
Labels: documentation

#953 Reinstate Highwater Tests in CI
  .github/workflows/applications.yml
Labels: component: mempool, component: project-config, component: testing

#956 Move the TXG
  chainweb.cabal
  tools/cwtool/CwTool.hs
  tools/txg/TXG.hs
  tools/txg/TXG/Repl.hs
  tools/txg/TXG/ReplInternals.hs
  tools/txg/TXG/Simulate/Contracts/CoinContract.hs
  tools/txg/TXG/Simulate/Contracts/Common.hs
  tools/txg/TXG/Simulate/Contracts/HelloWorld.hs
  tools/txg/TXG/Simulate/Contracts/SimplePayments.hs
  tools/txg/TXG/Simulate/Utils.hs
  tools/txg/TXG/Types.hs
  tools/txg/transaction-generator-help.md
Labels: component: tooling

#957 CPU Mining: Inject nonce bytes at the end
  CHANGELOG.md
  src/Chainweb/Miner/Core.hs
Labels: component: miner

#958 Don't cache GHC
  .github/workflows/stack-ci.yaml
Labels: component: project-config

#944 Timeless Payload Reassociation
  src/Chainweb/Chainweb/MinerResources.hs
  src/Chainweb/Logging/Miner.hs
  src/Chainweb/Miner/Coordinator.hs
  src/Chainweb/Miner/Miners.hs
  src/Chainweb/Miner/RestAPI/Server.hs
Labels: component: miner

#960 Updated binary encoding for BlockHeader
  src/Chainweb/BlockHeader.hs
Labels: component:core

#970 fix for db initialization in rest api tests
  test/Chainweb/Test/RestAPI.hs
  test/Chainweb/Test/Utils.hs
Labels: component: testing

#971 Run tests in stack CI
  .github/workflows/stack-ci.yaml
  stack.yaml
Labels: component: testing

#959 Fmelp/allocation tests
  pact/genesis/devnet/allocations.yaml
  pact/genesis/devnet/keysets.yaml
  src/Chainweb/BlockHeader/Genesis/Development0Payload.hs
  src/Chainweb/BlockHeader/Genesis/DevelopmentNPayload.hs
  src/Chainweb/BlockHeader/Genesis/FastTimedCPM0Payload.hs
  src/Chainweb/BlockHeader/Genesis/FastTimedCPMNPayload.hs
  test/golden/development-block-hashes-expected.txt
  test/golden/empty-block-tests-expected.txt
  test/golden/new-block-0-expected.txt
Labels: component: contract-data, component: testing

#977 compute epoch time based on parent header
  src/Chainweb/BlockHeader.hs
  src/Chainweb/Version.hs
Labels: Fork, component: cuts
